name: pyansys-env
channels:
  - conda-forge
  - robotology
dependencies:
  - python==3.11.0
  - numpy
  - tabulate
  - pip
  - pip:
    - ansys-geometry-core[all]==0.11.0
    - ansys-fluent-core==0.28.2
    - ansys-fluent-parametric
    - ansys-fluent-visualization
    - vtk
variables: # Change according to your installation
  AWP_ROOT251: "C:\\Program Files\\ANSYS Inc\\v251"
