# iRonCub-Mk3 config file

[Model]
Base_link = "root_link"

[Joints]
List = [
    "torso_pitch",
    "torso_roll",
    "torso_yaw",
    "l_shoulder_pitch",
    "l_shoulder_roll",
    "l_shoulder_yaw",
    "l_elbow",
    "r_shoulder_pitch",
    "r_shoulder_roll",
    "r_shoulder_yaw",
    "r_elbow",
    "l_hip_pitch",
    "l_hip_roll",
    "l_hip_yaw",
    "l_knee",
    "l_ankle_pitch",
    "l_ankle_roll",
    "r_hip_pitch",
    "r_hip_roll",
    "r_hip_yaw",
    "r_knee",
    "r_ankle_pitch",
    "r_ankle_roll",
]

[Surfaces]
List = [
    "ironcub_head",
    "ironcub_left_back_turbine",
    "ironcub_right_back_turbine",
    "ironcub_left_arm",
    "ironcub_left_arm_pitch",
    "ironcub_left_arm_roll",
    "ironcub_left_turbine",
    "ironcub_left_leg_lower",
    "ironcub_left_leg_pitch",
    "ironcub_left_leg_yaw",
    "ironcub_left_leg_upper",
    "ironcub_right_arm",
    "ironcub_right_arm_pitch",
    "ironcub_right_arm_roll",
    "ironcub_right_turbine",
    "ironcub_right_leg_lower",
    "ironcub_right_leg_pitch",
    "ironcub_right_leg_yaw",
    "ironcub_right_leg_upper",
    "ironcub_root_link",
    "ironcub_torso",
    "ironcub_torso_pitch",
    "ironcub_torso_roll",
]
Skip_list = [
    "ironcub_left_arm_pitch",
    "ironcub_left_arm_roll",
    "ironcub_right_arm_pitch",
    "ironcub_right_arm_roll",
    "ironcub_left_leg_pitch",
    "ironcub_left_leg_yaw",
    "ironcub_right_leg_pitch",
    "ironcub_right_leg_yaw",
    "ironcub_torso_pitch",
    "ironcub_torso_roll",
]
Merge_list = [
    "ironcub_left_arm",
    "ironcub_left_arm",
    "ironcub_right_arm",
    "ironcub_right_arm",
    "ironcub_left_leg_upper",
    "ironcub_left_leg_lower",
    "ironcub_right_leg_upper",
    "ironcub_right_leg_lower",
    "ironcub_torso",
    "ironcub_root_link",
]
Frames = [
    "head",
    "chest_l_jet_turbine",
    "chest_r_jet_turbine",
    "l_upper_arm",
    "l_shoulder_1",
    "l_shoulder_2",
    "l_arm_jet_turbine",
    "l_lower_leg",
    "l_hip_1",
    "l_upper_leg",
    "l_hip_3",
    "r_upper_arm",
    "r_shoulder_1",
    "r_shoulder_2",
    "r_arm_jet_turbine",
    "r_lower_leg",
    "r_hip_1",
    "r_upper_leg",
    "r_hip_3",
    "root_link",
    "chest",
    "torso_1",
    "torso_2",
]
Axes = [2, 2, 2, 2, 1, 0, 2, 2, 1, 2, 2, 2, 1, 0, 2, 2, 1, 2, 2, 2, 2, 2, 2]
Rot = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

[Meshes]
List = [
    "sim_head_head",
    "sim_head_neck_2",
    "sim_head_neck_3",
    "sim_icub3_chest",
    "sim_sea_3_jetpack",
    "sim_sea_l_jet_turbine",
    "sim_sea_r_jet_turbine",
    "sim_icub3_l_shoulder_1",
    "sim_icub3_l_shoulder_2",
    "sim_icub3_l_shoulder_3",
    "sim_icub3_l_upperarm",
    "sim_icub3_l_elbow_prosup",
    "sim_sea_l_arm_p250",
    "sim_icub3_r_shoulder_1",
    "sim_icub3_r_shoulder_2",
    "sim_icub3_r_shoulder_3",
    "sim_icub3_r_upperarm",
    "sim_icub3_r_elbow_prosup",
    "sim_sea_r_arm_p250",
    "sim_icub3_torso_2",
    "sim_icub3_torso_1",
    "sim_icub3_root_link",
    "sim_icub3_l_hip_1",
    "sim_icub3_l_hip_2",
    "sim_icub3_l_hip_3",
    "sim_icub3_l_upper_leg",
    "sim_icub3_l_lower_leg",
    "sim_icub3_l_ankle_1",
    "sim_icub3_l_ankle_2",
    "sim_icub3_l_foot_front",
    "sim_icub3_l_foot_rear",
    "sim_icub3_r_hip_1",
    "sim_icub3_r_hip_2",
    "sim_icub3_r_hip_3",
    "sim_icub3_r_upper_leg",
    "sim_icub3_r_lower_leg",
    "sim_icub3_r_ankle_1",
    "sim_icub3_r_ankle_2",
    "sim_icub3_r_foot_front",
    "sim_icub3_r_foot_rear",
]
Frames = [
    "head",
    "neck_2",
    "neck_3",
    "chest",
    "chest_jetpack",
    "chest_l_jet_turbine",
    "chest_r_jet_turbine",
    "l_shoulder_1",
    "l_shoulder_2",
    "l_shoulder_3",
    "l_upper_arm",
    "l_elbow_1",
    "l_arm_jet_turbine",
    "r_shoulder_1",
    "r_shoulder_2",
    "r_shoulder_3",
    "r_upper_arm",
    "r_elbow_1",
    "r_arm_jet_turbine",
    "torso_2",
    "torso_1",
    "root_link",
    "l_hip_1",
    "l_hip_2",
    "l_hip_3",
    "l_upper_leg",
    "l_lower_leg",
    "l_ankle_1",
    "l_ankle_2",
    "l_foot_front",
    "l_foot_rear",
    "r_hip_1",
    "r_hip_2",
    "r_hip_3",
    "r_upper_leg",
    "r_lower_leg",
    "r_ankle_1",
    "r_ankle_2",
    "r_foot_front",
    "r_foot_rear",
]
