name: pyfluent-env
channels:
  - conda-forge
  - robotology
  - open3d-admin
dependencies:
  - python
  - scipy
  - toml
  - idyntree
  - open3d
  - pip
  - pip:
    - ansys-fluent-core
    - ansys-fluent-parametric
    - ansys-fluent-visualization
    - vtk #==9.1.0
