name: pyfluent-env
channels:
  - conda-forge
  - robotology
dependencies:
  - python==3.11.0
  - numpy
  - pip
  - pip:
    - ansys-fluent-core==0.21.3
    - ansys-fluent-parametric
    - ansys-fluent-visualization
    - vtk #==9.1.0
