name: pyfluent-env
channels:
  - conda-forge
dependencies:
  - python #==3.9.0
  - pip
  - pip:
    - ansys-fluent-core
    - ansys-fluent-parametric
    - ansys-fluent-visualization
    - vtk #==9.1.0
